import type { UserRole } from '@/types/enums';

export type PermissionAction = 'view' | 'create' | 'edit' | 'delete' | 'export' | 'import';

export interface ModulePermissions {
  view: boolean;
  create: boolean;
  edit: boolean;
  delete: boolean;
  export?: boolean;
  import?: boolean;
}

export type PermissionMatrix = Record<UserRole, Record<string, ModulePermissions>>;

export const PERMISSIONS: PermissionMatrix = {
  SuperAdmin: {
    companies: { view: true, create: true, edit: true, delete: true, export: true, import: true },
    organizations: { view: true, create: true, edit: true, delete: true, export: true },
    agents: { view: true, create: true, edit: true, delete: true, export: true },
    transport: { view: true, create: true, edit: true, delete: true, export: true },
    dashboard: { view: true, create: false, edit: false, delete: false },
    shipments: { view: true, create: true, edit: true, delete: false, export: true },
    orders: { view: true, create: true, edit: true, delete: true, export: true },
    fleet: { view: true, create: true, edit: true, delete: true, export: true },
    drivers: { view: true, create: true, edit: true, delete: true, export: true },
    dispatch: { view: true, create: true, edit: true, delete: true, export: true },
    warehouse: { view: true, create: true, edit: true, delete: true, export: true },
    customers: { view: true, create: true, edit: true, delete: true, export: true },
    finance: { view: true, create: true, edit: true, delete: true, export: true },
    reports: { view: true, create: true, edit: true, delete: false, export: true },
    users: { view: true, create: true, edit: true, delete: true, export: true },
    settings: { view: true, create: true, edit: true, delete: true },
    notifications: { view: true, create: false, edit: false, delete: false },
  },

  OrganizationAdmin: {
    companies: { view: true, create: true, edit: true, delete: true, export: true, import: true },
    organizations: { view: true, create: false, edit: false, delete: false },
    agents: { view: true, create: false, edit: false, delete: false, export: true },
    transport: { view: true, create: false, edit: false, delete: false },
    dashboard: { view: true, create: false, edit: false, delete: false },
    shipments: { view: true, create: false, edit: false, delete: false, export: true },
    orders: { view: true, create: false, edit: false, delete: false, export: true },
    fleet: { view: true, create: false, edit: false, delete: false, export: true },
    drivers: { view: true, create: false, edit: false, delete: false, export: true },
    dispatch: { view: true, create: false, edit: false, delete: false, export: true },
    warehouse: { view: true, create: false, edit: false, delete: false, export: true },
    customers: { view: true, create: false, edit: false, delete: false, export: true },
    finance: { view: true, create: false, edit: false, delete: false, export: true },
    reports: { view: true, create: true, edit: false, delete: false, export: true },
    users: { view: true, create: true, edit: true, delete: true, export: true },
    settings: { view: true, create: false, edit: true, delete: false },
    notifications: { view: true, create: false, edit: false, delete: false },
  },
  CompanyAdmin: {
    companies: { view: true, create: false, edit: true, delete: false },
    organizations: { view: true, create: true, edit: true, delete: true, export: true },
    agents: { view: true, create: true, edit: true, delete: true, export: true },
    transport: { view: true, create: true, edit: true, delete: true, export: true },
    dashboard: { view: true, create: false, edit: false, delete: false },
    shipments: { view: true, create: true, edit: true, delete: false, export: true },
    orders: { view: true, create: true, edit: true, delete: true, export: true },
    fleet: { view: true, create: true, edit: true, delete: true, export: true },
    drivers: { view: true, create: true, edit: true, delete: true, export: true },
    dispatch: { view: true, create: true, edit: true, delete: true, export: true },
    warehouse: { view: true, create: true, edit: true, delete: true, export: true },
    customers: { view: true, create: true, edit: true, delete: true, export: true },
    finance: { view: true, create: true, edit: true, delete: true, export: true },
    reports: { view: true, create: true, edit: true, delete: false, export: true },
    users: { view: true, create: true, edit: true, delete: true, export: true },
    settings: { view: true, create: true, edit: true, delete: false },
    notifications: { view: true, create: false, edit: false, delete: false },
  },

  Manager: {
    companies: { view: true, create: false, edit: false, delete: false },
    organizations: { view: true, create: false, edit: false, delete: false },
    agents: { view: true, create: true, edit: true, delete: false, export: true },
    transport: { view: true, create: false, edit: false, delete: false },
    dashboard: { view: true, create: false, edit: false, delete: false },
    shipments: { view: true, create: true, edit: true, delete: false, export: true },
    orders: { view: true, create: true, edit: true, delete: false, export: true },
    fleet: { view: true, create: true, edit: true, delete: false, export: true },
    drivers: { view: true, create: true, edit: true, delete: false, export: true },
    dispatch: { view: true, create: true, edit: true, delete: false, export: true },
    warehouse: { view: true, create: true, edit: true, delete: false, export: true },
    customers: { view: true, create: true, edit: true, delete: false, export: true },
    finance: { view: true, create: false, edit: false, delete: false },
    reports: { view: true, create: true, edit: false, delete: false, export: true },
    users: { view: false, create: false, edit: false, delete: false },
    settings: { view: true, create: false, edit: true, delete: false },
    notifications: { view: true, create: false, edit: false, delete: false },
  },

  Dispatcher: {
    companies: { view: false, create: false, edit: false, delete: false },
    organizations: { view: false, create: false, edit: false, delete: false },
    agents: { view: false, create: false, edit: false, delete: false },
    transport: { view: false, create: false, edit: false, delete: false },
    dashboard: { view: true, create: false, edit: false, delete: false },
    shipments: { view: true, create: false, edit: true, delete: false, export: true },
    orders: { view: true, create: false, edit: false, delete: false },
    fleet: { view: true, create: false, edit: false, delete: false },
    drivers: { view: true, create: false, edit: false, delete: false },
    dispatch: { view: true, create: true, edit: true, delete: false, export: true },
    warehouse: { view: false, create: false, edit: false, delete: false },
    customers: { view: false, create: false, edit: false, delete: false },
    finance: { view: false, create: false, edit: false, delete: false },
    reports: { view: false, create: false, edit: false, delete: false },
    users: { view: false, create: false, edit: false, delete: false },
    settings: { view: false, create: false, edit: false, delete: false },
    notifications: { view: true, create: false, edit: false, delete: false },
  },

  Operator: {
    companies: { view: false, create: false, edit: false, delete: false },
    organizations: { view: false, create: false, edit: false, delete: false },
    agents: { view: false, create: false, edit: false, delete: false },
    transport: { view: false, create: false, edit: false, delete: false },
    dashboard: { view: true, create: false, edit: false, delete: false },
    shipments: { view: true, create: false, edit: true, delete: false, export: false },
    orders: { view: true, create: false, edit: false, delete: false },
    fleet: { view: true, create: false, edit: false, delete: false },
    drivers: { view: true, create: false, edit: false, delete: false },
    dispatch: { view: true, create: true, edit: true, delete: false },
    warehouse: { view: false, create: false, edit: false, delete: false },
    customers: { view: false, create: false, edit: false, delete: false },
    finance: { view: false, create: false, edit: false, delete: false },
    reports: { view: false, create: false, edit: false, delete: false },
    users: { view: false, create: false, edit: false, delete: false },
    settings: { view: false, create: false, edit: false, delete: false },
    notifications: { view: true, create: false, edit: false, delete: false },
  },

  Agent: {
    companies: { view: false, create: false, edit: false, delete: false },
    organizations: { view: false, create: false, edit: false, delete: false },
    agents: { view: false, create: false, edit: false, delete: false },
    transport: { view: false, create: false, edit: false, delete: false },
    dashboard: { view: true, create: false, edit: false, delete: false },
    shipments: { view: true, create: true, edit: true, delete: false, export: true },
    orders: { view: true, create: true, edit: true, delete: false, export: true },
    fleet: { view: false, create: false, edit: false, delete: false },
    drivers: { view: false, create: false, edit: false, delete: false },
    dispatch: { view: false, create: false, edit: false, delete: false },
    warehouse: { view: true, create: true, edit: true, delete: false, export: true },
    customers: { view: true, create: true, edit: true, delete: false, export: true },
    finance: { view: true, create: false, edit: false, delete: false },
    reports: { view: true, create: false, edit: false, delete: false, export: true },
    users: { view: false, create: false, edit: false, delete: false },
    settings: { view: false, create: false, edit: false, delete: false },
    notifications: { view: true, create: false, edit: false, delete: false },
  },

  Driver: {
    companies: { view: false, create: false, edit: false, delete: false },
    organizations: { view: false, create: false, edit: false, delete: false },
    agents: { view: false, create: false, edit: false, delete: false },
    transport: { view: false, create: false, edit: false, delete: false },
    dashboard: { view: true, create: false, edit: false, delete: false },
    shipments: { view: true, create: false, edit: true, delete: false },
    orders: { view: true, create: false, edit: false, delete: false },
    fleet: { view: false, create: false, edit: false, delete: false },
    drivers: { view: true, create: false, edit: false, delete: false },
    dispatch: { view: true, create: false, edit: false, delete: false },
    warehouse: { view: false, create: false, edit: false, delete: false },
    customers: { view: false, create: false, edit: false, delete: false },
    finance: { view: true, create: false, edit: false, delete: false },
    reports: { view: false, create: false, edit: false, delete: false },
    users: { view: false, create: false, edit: false, delete: false },
    settings: { view: false, create: false, edit: false, delete: false },
    notifications: { view: true, create: false, edit: false, delete: false },
    earnings: { view: true, create: false, edit: false, delete: false },
    pod: { view: true, create: true, edit: false, delete: false },
  },

  Staff: {
    companies: { view: false, create: false, edit: false, delete: false },
    organizations: { view: false, create: false, edit: false, delete: false },
    agents: { view: false, create: false, edit: false, delete: false },
    transport: { view: false, create: false, edit: false, delete: false },
    dashboard: { view: true, create: false, edit: false, delete: false },
    shipments: { view: true, create: true, edit: true, delete: false },
    orders: { view: true, create: true, edit: true, delete: false },
    fleet: { view: false, create: false, edit: false, delete: false },
    drivers: { view: false, create: false, edit: false, delete: false },
    dispatch: { view: false, create: false, edit: false, delete: false },
    warehouse: { view: true, create: true, edit: true, delete: false },
    customers: { view: true, create: true, edit: false, delete: false },
    finance: { view: true, create: false, edit: false, delete: false },
    reports: { view: true, create: false, edit: false, delete: false },
    users: { view: false, create: false, edit: false, delete: false },
    settings: { view: false, create: false, edit: false, delete: false },
    notifications: { view: true, create: false, edit: false, delete: false },
  },

  CustomsAgent: {
    companies: { view: false, create: false, edit: false, delete: false },
    organizations: { view: false, create: false, edit: false, delete: false },
    agents: { view: false, create: false, edit: false, delete: false },
    transport: { view: false, create: false, edit: false, delete: false },
    dashboard: { view: true, create: false, edit: false, delete: false },
    shipments: { view: true, create: false, edit: true, delete: false, export: true },
    orders: { view: false, create: false, edit: false, delete: false },
    fleet: { view: false, create: false, edit: false, delete: false },
    drivers: { view: false, create: false, edit: false, delete: false },
    dispatch: { view: false, create: false, edit: false, delete: false },
    warehouse: { view: false, create: false, edit: false, delete: false },
    customers: { view: false, create: false, edit: false, delete: false },
    finance: { view: false, create: false, edit: false, delete: false },
    reports: { view: true, create: false, edit: false, delete: false, export: true },
    users: { view: false, create: false, edit: false, delete: false },
    settings: { view: false, create: false, edit: false, delete: false },
    notifications: { view: true, create: false, edit: false, delete: false },
    compliance: { view: true, create: true, edit: true, delete: false },
    documents: { view: true, create: true, edit: true, delete: false },
  },

  PortAgent: {
    companies: { view: false, create: false, edit: false, delete: false },
    organizations: { view: false, create: false, edit: false, delete: false },
    agents: { view: false, create: false, edit: false, delete: false },
    transport: { view: false, create: false, edit: false, delete: false },
    dashboard: { view: true, create: false, edit: false, delete: false },
    shipments: { view: true, create: false, edit: true, delete: false, export: true },
    orders: { view: false, create: false, edit: false, delete: false },
    fleet: { view: false, create: false, edit: false, delete: false },
    drivers: { view: false, create: false, edit: false, delete: false },
    dispatch: { view: false, create: false, edit: false, delete: false },
    warehouse: { view: false, create: false, edit: false, delete: false },
    customers: { view: false, create: false, edit: false, delete: false },
    finance: { view: true, create: false, edit: false, delete: false },
    reports: { view: true, create: false, edit: false, delete: false, export: true },
    users: { view: false, create: false, edit: false, delete: false },
    settings: { view: false, create: false, edit: false, delete: false },
    notifications: { view: true, create: false, edit: false, delete: false },
    documents: { view: true, create: true, edit: true, delete: false },
  },

  CustomerPortal: {
    companies: { view: false, create: false, edit: false, delete: false },
    organizations: { view: false, create: false, edit: false, delete: false },
    agents: { view: false, create: false, edit: false, delete: false },
    transport: { view: false, create: false, edit: false, delete: false },
    dashboard: { view: true, create: false, edit: false, delete: false },
    shipments: { view: true, create: false, edit: false, delete: false },
    orders: { view: true, create: true, edit: false, delete: false },
    fleet: { view: false, create: false, edit: false, delete: false },
    drivers: { view: false, create: false, edit: false, delete: false },
    dispatch: { view: false, create: false, edit: false, delete: false },
    warehouse: { view: false, create: false, edit: false, delete: false },
    customers: { view: false, create: false, edit: false, delete: false },
    finance: { view: true, create: false, edit: false, delete: false },
    reports: { view: false, create: false, edit: false, delete: false },
    users: { view: false, create: false, edit: false, delete: false },
    settings: { view: false, create: false, edit: false, delete: false },
    notifications: { view: true, create: false, edit: false, delete: false },
    bookings: { view: true, create: true, edit: false, delete: false },
    documents: { view: true, create: false, edit: false, delete: false },
    support: { view: true, create: true, edit: false, delete: false },
  },

  AuditorReadOnly: {
    companies: { view: true, create: false, edit: false, delete: false, export: true },
    organizations: { view: true, create: false, edit: false, delete: false, export: true },
    agents: { view: true, create: false, edit: false, delete: false, export: true },
    transport: { view: true, create: false, edit: false, delete: false, export: true },
    dashboard: { view: true, create: false, edit: false, delete: false },
    shipments: { view: true, create: false, edit: false, delete: false, export: true },
    orders: { view: true, create: false, edit: false, delete: false, export: true },
    fleet: { view: true, create: false, edit: false, delete: false, export: true },
    drivers: { view: true, create: false, edit: false, delete: false, export: true },
    dispatch: { view: true, create: false, edit: false, delete: false, export: true },
    warehouse: { view: true, create: false, edit: false, delete: false, export: true },
    customers: { view: true, create: false, edit: false, delete: false, export: true },
    finance: { view: true, create: false, edit: false, delete: false, export: true },
    reports: { view: true, create: false, edit: false, delete: false, export: true },
    users: { view: true, create: false, edit: false, delete: false, export: true },
    settings: { view: false, create: false, edit: false, delete: false },
    notifications: { view: true, create: false, edit: false, delete: false },
    compliance: { view: true, create: false, edit: false, delete: false },
    logs: { view: true, create: false, edit: false, delete: false },
  },
};
