/database/sql/schema/0003_create_companies_table.sql
-- Create companies table to store all logistics companies
CREATE TABLE IF NOT EXISTS `companies` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `uuid` CHAR(36) NOT NULL UNIQUE COMMENT 'Public unique identifier',
  `company_type_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `registration_number` VARCHAR(100) NULL UNIQUE,
  `tax_id` VARCHAR(50) NULL,
  `email` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `website` VARCHAR(255) NULL,
  `address_line1` TEXT NULL,
  `address_line2` TEXT NULL,
  `city` VARCHAR(100) NULL,
  `state` VARCHAR(100) NULL,
  `country` VARCHAR(100) NULL,
  `postal_code` VARCHAR(20) NULL,
  `subscription_status` ENUM('trial', 'active', 'suspended', 'cancelled') NOT NULL DEFAULT 'trial',
  `subscription_start_date` DATE NULL,
  `subscription_end_date` DATE NULL,
  `status` ENUM('pending', 'active', 'suspended', 'inactive') NOT NULL DEFAULT 'pending',
  `is_verified` BOOLEAN NOT NULL DEFAULT FALSE,
  `verified_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  FOREIGN KEY (`company_type_id`) REFERENCES `company_types`(`id`) ON DELETE RESTRICT,
  INDEX idx_companies_uuid (`uuid`),
  INDEX idx_companies_company_type_id (`company_type_id`),
  INDEX idx_companies_status (`status`),
  INDEX idx_companies_subscription_status (`subscription_status`),
  INDEX idx_companies_deleted_at (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;