-- Create organizations table for multi-organization management
CREATE TABLE IF NOT EXISTS `organizations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `uuid` CHAR(36) NOT NULL UNIQUE COMMENT 'Public unique identifier',
  `name` VARCHAR(255) NOT NULL,
  `registration_number` VARCHAR(100) NULL UNIQUE,
  `tax_id` VARCHAR(50) NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(50) NULL,
  `website` VARCHAR(255) NULL,
  `address_line1` TEXT NULL,
  `address_line2` TEXT NULL,
  `city` VARCHAR(100) NULL,
  `state` VARCHAR(100) NULL,
  `country` VARCHAR(100) NULL,
  `postal_code` VARCHAR(20) NULL,
  `subscription_status` ENUM('trial', 'active', 'suspended', 'cancelled') NOT NULL DEFAULT 'trial',
  `subscription_start_date` DATE NULL,
  `subscription_end_date` DATE NULL,
  `max_companies` INT UNSIGNED NOT NULL DEFAULT 10 COMMENT 'Maximum number of companies allowed',
  `max_users_per_company` INT UNSIGNED NOT NULL DEFAULT 50 COMMENT 'Maximum users per company',
  `status` ENUM('pending', 'active', 'suspended', 'inactive') NOT NULL DEFAULT 'pending',
  `is_verified` BOOLEAN NOT NULL DEFAULT FALSE,
  `verified_at` TIMESTAMP NULL,
  `verified_by` INT UNSIGNED NULL COMMENT 'User ID who verified the organization',
  `created_by` INT UNSIGNED NULL COMMENT 'User ID who created the organization',
  `updated_by` INT UNSIGNED NULL COMMENT 'User ID who last updated the organization',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  FOREIGN KEY (`verified_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`updated_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  INDEX idx_organizations_uuid (`uuid`),
  INDEX idx_organizations_email (`email`),
  INDEX idx_organizations_status (`status`),
  INDEX idx_organizations_subscription_status (`subscription_status`),
  INDEX idx_organizations_deleted_at (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
