-- Create organization_users table for organization-level user management
CREATE TABLE IF NOT EXISTS `organization_users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `uuid` CHAR(36) NOT NULL UNIQUE COMMENT 'Public unique identifier',
  `organization_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `role_id` INT UNSIGNED NOT NULL COMMENT 'Role within the organization',
  `approval_status` ENUM('pending', 'approved', 'rejected', 'suspended') NOT NULL DEFAULT 'pending',
  `approved_at` TIMESTAMP NULL,
  `approved_by` INT UNSIGNED NULL COMMENT 'User ID who approved',
  `rejected_at` TIMESTAMP NULL,
  `rejected_by` INT UNSIGNED NULL COMMENT 'User ID who rejected',
  `rejection_reason` TEXT NULL,
  `suspended_at` TIMESTAMP NULL,
  `suspended_by` INT UNSIGNED NULL COMMENT 'User ID who suspended',
  `suspension_reason` TEXT NULL,
  `reactivated_at` TIMESTAMP NULL,
  `reactivated_by` INT UNSIGNED NULL COMMENT 'User ID who reactivated',
  `is_primary_contact` BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'Primary contact for organization',
  `department` VARCHAR(100) NULL,
  `job_title` VARCHAR(100) NULL,
  `created_by` INT UNSIGNED NULL COMMENT 'User ID who created the organization user',
  `updated_by` INT UNSIGNED NULL COMMENT 'User ID who last updated',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`role_id`) REFERENCES `roles`(`id`) ON DELETE RESTRICT,
  FOREIGN KEY (`approved_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`rejected_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`suspended_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`reactivated_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`updated_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  UNIQUE KEY `unique_org_user` (`organization_id`, `user_id`),
  INDEX idx_organization_users_uuid (`uuid`),
  INDEX idx_organization_users_organization_id (`organization_id`),
  INDEX idx_organization_users_user_id (`user_id`),
  INDEX idx_organization_users_role_id (`role_id`),
  INDEX idx_organization_users_approval_status (`approval_status`),
  INDEX idx_organization_users_deleted_at (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
