-- Create approval_requests table for centralized approval workflow management
CREATE TABLE IF NOT EXISTS `approval_requests` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `uuid` CHAR(36) NOT NULL UNIQUE COMMENT 'Public unique identifier',
  `request_type` ENUM('organization_user', 'company_user', 'company', 'organization') NOT NULL,
  `request_id` INT UNSIGNED NOT NULL COMMENT 'ID of the entity requesting approval',
  `requested_by` INT UNSIGNED NOT NULL COMMENT 'User ID who initiated the request',
  `approval_status` ENUM('pending', 'approved', 'rejected', 'suspended') NOT NULL DEFAULT 'pending',
  `approved_at` TIMESTAMP NULL,
  `approved_by` INT UNSIGNED NULL COMMENT 'User ID who approved',
  `rejected_at` TIMESTAMP NULL,
  `rejected_by` INT UNSIGNED NULL COMMENT 'User ID who rejected',
  `rejection_reason` TEXT NULL,
  `suspended_at` TIMESTAMP NULL,
  `suspended_by` INT UNSIGNED NULL COMMENT 'User ID who suspended',
  `suspension_reason` TEXT NULL,
  `reactivated_at` TIMESTAMP NULL,
  `reactivated_by` INT UNSIGNED NULL COMMENT 'User ID who reactivated',
  `notes` TEXT NULL COMMENT 'Additional notes or comments',
  `metadata` JSON NULL COMMENT 'Additional request-specific data',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  FOREIGN KEY (`requested_by`) REFERENCES `users`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`approved_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`rejected_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`suspended_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`reactivated_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  INDEX idx_approval_requests_uuid (`uuid`),
  INDEX idx_approval_requests_type (`request_type`),
  INDEX idx_approval_requests_request_id (`request_id`),
  INDEX idx_approval_requests_requested_by (`requested_by`),
  INDEX idx_approval_requests_status (`approval_status`),
  INDEX idx_approval_requests_deleted_at (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
